name: deploy-prod

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  prod-smoke:
    name: prod-smoke
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::444198540044:role/GitHubActions-ProdDeployRole
          aws-region: eu-central-1

      - name: Pre-check PROD health (/health)
        run: |
          curl -fsS "${{ vars.PROD_HEALTH_URL }}"

      - name: Deploy PROD (ASG Instance Refresh)
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "${{ vars.PROD_ASG_NAME }}" \
            --preferences MinHealthyPercentage=90,InstanceWarmup=60

      - name: Wait for PROD deploy to finish
        run: |
          REFRESH_ID=$(aws autoscaling describe-instance-refreshes \
            --auto-scaling-group-name "${{ vars.PROD_ASG_NAME }}" \
            --query "InstanceRefreshes[0].InstanceRefreshId" --output text)

          echo "Refresh ID: $REFRESH_ID"

          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name "${{ vars.PROD_ASG_NAME }}" \
              --instance-refresh-ids "$REFRESH_ID" \
              --query "InstanceRefreshes[0].Status" --output text)

            echo "PROD refresh status: $STATUS"

            if [ "$STATUS" = "Successful" ]; then exit 0; fi
            if [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then exit 1; fi
            sleep 20
          done

      - name: Post-check PROD health (/health)
        run: |
          curl -fsS "${{ vars.PROD_HEALTH_URL }}"
